/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CarbonFootprintEntry = IDL.Record({
  'gas' : IDL.Float64,
  'transportation' : IDL.Float64,
  'electricity' : IDL.Float64,
  'totalCO2' : IDL.Float64,
  'timestamp' : IDL.Int,
  'waste' : IDL.Float64,
});
export const UserLevel = IDL.Variant({
  'ecoWarrior' : IDL.Null,
  'beginner' : IDL.Null,
  'greenChampion' : IDL.Null,
});
export const EntryInput = IDL.Record({
  'gas' : IDL.Float64,
  'transportation' : IDL.Float64,
  'electricity' : IDL.Float64,
  'waste' : IDL.Float64,
});
export const EntryResult = IDL.Record({
  'ecoScore' : IDL.Nat,
  'totalCO2' : IDL.Float64,
  'ecoPoints' : IDL.Nat,
  'carbonLevel' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(CarbonFootprintEntry)], ['query']),
  'getLatestEntry' : IDL.Func([], [IDL.Opt(CarbonFootprintEntry)], ['query']),
  'getTotalPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserLevel' : IDL.Func([], [UserLevel], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEntry' : IDL.Func([EntryInput], [EntryResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CarbonFootprintEntry = IDL.Record({
    'gas' : IDL.Float64,
    'transportation' : IDL.Float64,
    'electricity' : IDL.Float64,
    'totalCO2' : IDL.Float64,
    'timestamp' : IDL.Int,
    'waste' : IDL.Float64,
  });
  const UserLevel = IDL.Variant({
    'ecoWarrior' : IDL.Null,
    'beginner' : IDL.Null,
    'greenChampion' : IDL.Null,
  });
  const EntryInput = IDL.Record({
    'gas' : IDL.Float64,
    'transportation' : IDL.Float64,
    'electricity' : IDL.Float64,
    'waste' : IDL.Float64,
  });
  const EntryResult = IDL.Record({
    'ecoScore' : IDL.Nat,
    'totalCO2' : IDL.Float64,
    'ecoPoints' : IDL.Nat,
    'carbonLevel' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(CarbonFootprintEntry)], ['query']),
    'getLatestEntry' : IDL.Func([], [IDL.Opt(CarbonFootprintEntry)], ['query']),
    'getTotalPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserLevel' : IDL.Func([], [UserLevel], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEntry' : IDL.Func([EntryInput], [EntryResult], []),
  });
};

export const init = ({ IDL }) => { return []; };