/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CarbonFootprintEntry {
  'gas' : number,
  'transportation' : number,
  'electricity' : number,
  'totalCO2' : number,
  'timestamp' : bigint,
  'waste' : number,
}
export interface EntryInput {
  'gas' : number,
  'transportation' : number,
  'electricity' : number,
  'waste' : number,
}
export interface EntryResult {
  'ecoScore' : bigint,
  'totalCO2' : number,
  'ecoPoints' : bigint,
  'carbonLevel' : string,
}
export type UserLevel = { 'ecoWarrior' : null } |
  { 'beginner' : null } |
  { 'greenChampion' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHistory' : ActorMethod<[], Array<CarbonFootprintEntry>>,
  'getLatestEntry' : ActorMethod<[], [] | [CarbonFootprintEntry]>,
  'getTotalPoints' : ActorMethod<[], bigint>,
  'getUserLevel' : ActorMethod<[], UserLevel>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitEntry' : ActorMethod<[EntryInput], EntryResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];